---
- name: Create each user and ensure that they are all in DB2USERS
  hosts: db2dev.ifmssystem.com
  tasks: 
  
    - name: Ensure user contentown is present
      win_user:
        name: contentown
        fullname: "contentown"
        description: "db2 schema owner for COGCON database"
        password: "{{ contentownpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user cpagc is present
      win_user:
        name: cpagc
        fullname: "cpagc"
        description: "db2 schema owner in MASTER database"
        password: "{{ cpagcpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user cpgsa is present
      win_user:
        name: cpgsa
        fullname: "cpgsa"
        description: "db2 schema owner for GSADB database"
        password: "{{ cpgsapw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user cpuser is present
      win_user:
        name: cpuser
        fullname: "cpuser"
        description: "db2 schema owner in MASTER database"
        password: "{{ cpuserpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user exagc is present
      win_user:
        name: exagc
        fullname: "exagc"
        description: "db2 schema owner in MASTER database"
        password: "{{ exagcpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user exfti is present
      win_user:
        name: exfti
        fullname: "exfti"
        description: "db2 schema owner in MASTER database"
        password: "{{ exftipw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user exgsa is present
      win_user:
        name: exgsa
        fullname: "exgsa"
        description: "db2 schema owner in GSADB database"
        password: "{{ exgsapw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user exuser is present
      win_user:
        name: exuser
        fullname: "exuser"
        description: "db2 schema owner in MASTER and GSADB databases"
        password: "{{ exuserpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user gsaowner is present
      win_user:
        name: gsaowner
        fullname: "gsaowner"
        description: "principal schema owner in GSADB database"
        password: "{{ gsaownerpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user iceuser is present
      win_user:
        name: iceuser
        fullname: "ICE"
        description: "expense tool"
        password: "{{ iceuserpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user ifmsuser is present
      win_user:
        name: ifmsuser
        fullname: "ifmsuser"
        description: "website user for Reporting databases"
        password: "{{ ifmsuserpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user loggingown is present
      win_user:
        name: loggingown
        fullname: "loggingown"
        description: "db2 schema owner for COGLOG database"
        password: "{{ loggingownpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user mstowner is present
      win_user:
        name: mstowner
        fullname: "mstowner"
        description: "db2 schema owner for MASTER database"
        password: "{{ mstownerpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user qatest is present
      win_user:
        name: qatest
        fullname: "qatest"
        description: "QA test account"
        password: "{{ qatestpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    - name: Ensure user tfmsowner is present
      win_user:
        name: tfmsowner
        fullname: "tfmsowner"
        description: "db2 schema owner"
        password: "{{ tfmsownerpw }}"
        password_never_expires: yes
        password_expired: no
        state: present
        groups_action: add
        user_cannot_change_password: yes
        groups:
        - DB2USERS
        
    # log is written to d:\temp
    - name: list users in all local groups
      script: ListUsers.ps1
      register: list_result
      
...