 - name: Confirm that DB2_GRP_LOOKUP is set
   hosts: db2d.ifms.dev
          db2t.ifms.dev
          proto.ifms.dev
          # db2p.ifms.dev
          # db2rp.ifms.dev
          # db2f.ifms.dev
          # db2rf.ifms.dev
   tasks: 

    - name: Ensure that the DB2_GRP_LOOKUP environmental variable is set correctly
      script: ConfirmDB2_GRP_LOOKUP.ps1
 
            
